#!/bin/sh -e
if [ $# -ne 2 ]; then
    echo usage: $(basename $0) INFILE OUTFILE
    exit 1
fi
kcfile="$1"
binfile="$2"

flags="--emit-x64"

# cat ${kcfile} >&2
# echo ' =========== ' >&2
# ./main ${flags} ${kcfile} >&2
# echo ' =========== ' >&2
./main ${flags} ${kcfile} | cc -w -x assembler -m32 -o ${binfile} -
